export const GET_UPDATING_REPORT = 'GET_UPDATING_REPORT';
export const GET_LIST_REPORTS = 'GET_LIST_REPORTS';
export const GET_VIEW_HELPER_OPEN = 'GET_VIEW_HELPER_OPEN';
export const GET_VIEW_HELPER_UPDATING = 'GET_VIEW_HELPER_OPEN';